# Generated by Django 2.0.1 on 2018-01-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180127_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='body',
        ),
    ]
